FROM node:22-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Expose Vite's port
EXPOSE 3000

# Start Vite development server
CMD ["npm", "run", "dev"]
