FROM node:22-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Expose Backend port
EXPOSE 5001

# Start the Node.js watch server
CMD ["npm", "run", "dev"]
